version: "3.9"
services:
  drift-detect-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: drift-detect:latest
    container_name: drift-detect-service
    environment:
      - DDS_SETTINGS=/app/config/settings.yaml
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config:ro